/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PgRouteImport } from './routes/pg'
import { Route as HostelRouteImport } from './routes/hostel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PgIndexRouteImport } from './routes/pg.index'
import { Route as PgVanaraji9thFloorRouteImport } from './routes/pg.vanaraji-9th-floor'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PgRoute = PgRouteImport.update({
  id: '/pg',
  path: '/pg',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelRoute = HostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PgIndexRoute = PgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PgRoute,
} as any)
const PgVanaraji9thFloorRoute = PgVanaraji9thFloorRouteImport.update({
  id: '/vanaraji-9th-floor',
  path: '/vanaraji-9th-floor',
  getParentRoute: () => PgRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hostel': typeof HostelRoute
  '/pg': typeof PgRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/pg/vanaraji-9th-floor': typeof PgVanaraji9thFloorRoute
  '/pg/': typeof PgIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hostel': typeof HostelRoute
  '/privacy': typeof PrivacyRoute
  '/pg/vanaraji-9th-floor': typeof PgVanaraji9thFloorRoute
  '/pg': typeof PgIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hostel': typeof HostelRoute
  '/pg': typeof PgRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/pg/vanaraji-9th-floor': typeof PgVanaraji9thFloorRoute
  '/pg/': typeof PgIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hostel'
    | '/pg'
    | '/privacy'
    | '/pg/vanaraji-9th-floor'
    | '/pg/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hostel' | '/privacy' | '/pg/vanaraji-9th-floor' | '/pg'
  id:
    | '__root__'
    | '/'
    | '/hostel'
    | '/pg'
    | '/privacy'
    | '/pg/vanaraji-9th-floor'
    | '/pg/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostelRoute: typeof HostelRoute
  PgRoute: typeof PgRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pg': {
      id: '/pg'
      path: '/pg'
      fullPath: '/pg'
      preLoaderRoute: typeof PgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostel': {
      id: '/hostel'
      path: '/hostel'
      fullPath: '/hostel'
      preLoaderRoute: typeof HostelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pg/': {
      id: '/pg/'
      path: '/'
      fullPath: '/pg/'
      preLoaderRoute: typeof PgIndexRouteImport
      parentRoute: typeof PgRoute
    }
    '/pg/vanaraji-9th-floor': {
      id: '/pg/vanaraji-9th-floor'
      path: '/vanaraji-9th-floor'
      fullPath: '/pg/vanaraji-9th-floor'
      preLoaderRoute: typeof PgVanaraji9thFloorRouteImport
      parentRoute: typeof PgRoute
    }
  }
}

interface PgRouteChildren {
  PgVanaraji9thFloorRoute: typeof PgVanaraji9thFloorRoute
  PgIndexRoute: typeof PgIndexRoute
}

const PgRouteChildren: PgRouteChildren = {
  PgVanaraji9thFloorRoute: PgVanaraji9thFloorRoute,
  PgIndexRoute: PgIndexRoute,
}

const PgRouteWithChildren = PgRoute._addFileChildren(PgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostelRoute: HostelRoute,
  PgRoute: PgRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
