/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HostelRouteImport } from './routes/hostel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PgIndexRouteImport } from './routes/pg.index'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelRoute = HostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PgIndexRoute = PgIndexRouteImport.update({
  id: '/pg/',
  path: '/pg/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hostel': typeof HostelRoute
  '/privacy': typeof PrivacyRoute
  '/pg/': typeof PgIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hostel': typeof HostelRoute
  '/privacy': typeof PrivacyRoute
  '/pg': typeof PgIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hostel': typeof HostelRoute
  '/privacy': typeof PrivacyRoute
  '/pg/': typeof PgIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hostel' | '/privacy' | '/pg/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hostel' | '/privacy' | '/pg'
  id: '__root__' | '/' | '/hostel' | '/privacy' | '/pg/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostelRoute: typeof HostelRoute
  PrivacyRoute: typeof PrivacyRoute
  PgIndexRoute: typeof PgIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostel': {
      id: '/hostel'
      path: '/hostel'
      fullPath: '/hostel'
      preLoaderRoute: typeof HostelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pg/': {
      id: '/pg/'
      path: '/pg'
      fullPath: '/pg/'
      preLoaderRoute: typeof PgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostelRoute: HostelRoute,
  PrivacyRoute: PrivacyRoute,
  PgIndexRoute: PgIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
